apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: cluster-project
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-project
type: Opaque
stringData:
  username: "app"
  password: "change_me"
---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uris
  namespace: cluster-project
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-project
type: Opaque
stringData:
  AUTH_MONGODB_URI: "mongodb://app:change_me@mongodb:27017/auth?authSource=admin&directConnection=true"
  PRODUCT_MONGODB_URI: "mongodb://app:change_me@mongodb:27017/products?authSource=admin&directConnection=true"
  ORDER_MONGODB_URI: "mongodb://app:change_me@mongodb:27017/orders?authSource=admin&directConnection=true"
---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: cluster-project
  labels:
    app.kubernetes.io/part-of: cluster-project
type: Opaque
stringData:
  JWT_SECRET: "change_me"
